### ISSUE TITLE
Fix some tslint errors for typesript model generator

### ISSUE THREAD

**Issue by Simply007** [Enngage/KenticoCloudModelGeneratorUtility#10]
I have used generator for generating models using:
`kc-generate --ts --projectId <projectId> --definitions`

My [tslit.json](https://github.com/Kentico/cloud-sample-pwa-app/blob/v3-angular/tslint.json).

Result has these errors:
![image](https://user-images.githubusercontent.com/9218736/38249189-21222d8c-374b-11e8-8ceb-57771ac63f52.png)

**Comment by Enngage** [comment]
Should be fixed in `0.10.0` release
