### ISSUE TITLE
Package.json does not contains ling for the repository

### ISSUE THREAD

**Issue by Simply007** [Enngage/KenticoCloudModelGeneratorUtility#11]
On the npm, there is no link to the git repository:
https://www.npmjs.com/package/kentico-cloud-model-generator-utility

This link should fixed by providing the link to the package,json in fomat **similar** like (not sure about exact format):
```
...
"repository": {
        "type": "git",
        "url": "git+https://github.com/Enngage/KenticoCloudModelGeneratorUtility.git"
    }
...
```

**Comment by Enngage** [comment]
Fixed by https://github.com/Enngage/KenticoCloudModelGeneratorUtility/commit/cbef3b39e091349bb270ffd33680c3a9f1933719
