### ISSUE TITLE
Generated models not valid

### ISSUE THREAD

**Issue by ChristopherJennings** [Enngage/KenticoCloudModelGeneratorUtility#2]
Similar to the the previous [documentation issue in the SDK](https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK/pull/3), the generated classes are not strictly valid as they don't return the fieldName in the generated proprtyResolver after all the `if` blocks. Additionally, `IContentItem` is included but unused.

**Comment by ChristopherJennings** [comment]
Just realized that `IContentItem` is used if you have modular content... I guess maybe including that needs to be conditional.

**Comment by Enngage** [comment]
Could you more elaborate on what you mean? 
 
Are you talking about the fact that no `fieldName `is returned after the last if in e.g following code?
```
constructor(){
        super({
            propertyResolver: ((fieldName: string) => {
                
                if (fieldName === 'product_name'){
                    return 'productName';
                }
             })
        })    
    }
```

If so, then it is a correct behavior as if nothing is returned, original property name will be used for binding. 

Also what you mean by conditional `IContent `item? Any example?

**Comment by ChristopherJennings** [comment]
So, maybe I'm just not familiar with the JS syntax, but in order for the fieldName to return if none of the if blocks were valid you'd need to add the return. At least, in my case linting was showing that as necessary:
```javascript
constructor(){
  super({
    propertyResolver: ((fieldName: string) => {            
      if (fieldName === 'product_name'){
        return 'productName';
      }
      return fieldName;
    })
  })    
}
```

IContent is only required if you had a field that is a modular content field. If your content type doesn't have one of those, the import of IContent is unnecessary, and in my case my linter doesn't like unnecessary imports.

**Comment by Enngage** [comment]
I've removed IContentItem from imports if the class does not contain any modular content fields. 

Returning field name from the propertyResolver is really not necessary. There is a code in [MapService class](https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK/blob/master/lib/services/field-map.service.ts) that tries to resolve the field name using the resolver function, but if its resolved to null/undefined/empty, it will use the 'codename' of the field out of the Kentico Cloud:
```
// resolve field to a custom model property
if (itemTyped.propertyResolver) {
   propertyName = itemTyped.propertyResolver(fieldName);
}
 // if property name is null/empty, use elements codename
 if (!propertyName) {
      propertyName = fieldName;
 }
```
I checked my Angular app, and it seems to work ok :-)

**Comment by ChristopherJennings** [comment]
Ah, I see. In other words, the code that calls this resolver safely handles the final return not being present. I'd argue that it would still be "better" to add it in explicitly. This way you don't get linting errors such as the one that brought this to my attention.

**Comment by Enngage** [comment]
I'm using the latest Visual studio code & it has no issues with this code whatsoever. What IDE you are using? WebStorm?

I don't think this goes against any code rules. Actually I initially had the return in the code, but then decided to get rid of it as it is unnecessary.

**Comment by ChristopherJennings** [comment]
I'm using Visual Studio Code. I spun up a React starter site with TypeScript ([per their docs](https://github.com/Microsoft/TypeScript-React-Starter#typescript-react-starter)). This starter projec includes a tsconfig.json with some rules specified. I narrowed it down to two rules that were causing the errors I was seeing in the generated models: `noImplicitReturns` and `strictNullCheck`. Given that both of these rules are satisfied by adding the return of the fieldname and they seem like they'd be fairly common rules (they're in the TypeScript/React starter) I'd say it's probably best to specify the return.

**Comment by Enngage** [comment]
Ah, I see. This is a really good point. Technically speaking, it doesn't matter, but it might be nice to have this incorporated by default. I'll adjust the documentation based on this.

**Comment by Enngage** [comment]
I added support for strict null checks & implicit returns in the main SDK -> https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK/issues/10

**Comment by Enngage** [comment]
I added support for strict null checks & implicit returns in the main SDK -> Enngage/KenticoCloudDeliveryTypeScriptSDK#10 

+ I changed the code generator to explicitly return fieldName. I belive this should be all, or is there something else to this?

**Comment by ChristopherJennings** [comment]
This does indeed solve the issue. Thanks!
